import "@/public/globals.css"
import type { Metadata } from "next"
import { Gabarito } from "next/font/google"
import localFont from "next/font/local"
import { ReactNode } from "react"
import { Topography } from "@/components/server/common/Topography"
import { i18n } from "@/root/i18n-config"

const gabarito = Gabarito({ subsets: ["latin"], display: "swap", variable: "--font-gabarito" })

const sfmono = localFont({
  src: [
    {
      path: "../../../public/fonts/SFMono/SFMonoMedium.woff2",
      weight: "500",
      style: "normal"
    },
    {
      path: "../../../public/fonts/SFMono/SFMonoSemibold.woff2",
      weight: "600",
      style: "normal"
    },
    {
      path: "../../../public/fonts/SFMono/SFMonoSemiboldItalic.woff2",
      weight: "600",
      style: "italic"
    }
  ],
  display: "swap",
  variable: "--font-sfmono"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({ children, params }: { children: ReactNode; params: { lang: string } }) {
  return (
    <html lang={params.lang}>
      <body className={`${gabarito.variable} ${sfmono.variable} font-gabarito`}>
        <main className="relative">
          {children}
          <div className="absolute inset-0 z-[-1] h-full opacity-5">
            <Topography />
          </div>
        </main>
      </body>
    </html>
  )
}
