import "../../public/globals.css"
import type { Metadata } from "next"
import { Gabarito } from "next/font/google"
import localFont from "next/font/local"
import { ReactNode } from "react"

const gabarito = Gabarito({ subsets: ["latin"], display: "swap", variable: "--font-gabarito" })

const sfmono = localFont({
  src: [
    {
      path: "../../public/fonts/SFMono/SFMonoMedium.woff2",
      weight: "500",
      style: "normal"
    },
    {
      path: "../../public/fonts/SFMono/SFMonoSemibold.woff2",
      weight: "600",
      style: "normal"
    },
    {
      path: "../../public/fonts/SFMono/SFMonoSemiboldItalic.woff2",
      weight: "600",
      style: "italic"
    }
  ],
  display: "swap",
  variable: "--font-sfmono"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body className={`${gabarito.variable} ${sfmono.variable} bg-opacity-50 font-gabarito`}>
        <main className="relative">
          {children}
          <div className="absolute inset-0 h-full bg-topography-pattern bg-repeat opacity-5"></div>
        </main>
      </body>
    </html>
  )
}
